ecomapp/urls.py
from django.urls import path
from .views import HomeView,AboutView,AllProductsView,ProductDetailView

app_name = "ecomapp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/",AboutView.as_view(), name="about"),
    path("all-products/",AllProductsView.as_view(), name="allproducts"),
    path("products/<slug:slug>/",ProductDetailView.as_view(), name="productdetail"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null= True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title
    

class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart:" + str(self.id)
    
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete= models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart:" + str(self.cart.id) + "CartProduct:" + str(self.id)
    

ORDER_STATUS = (
    ("Order Received","Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),

)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order:" + str(self.id) 

ecomapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import *
# Create your views here.

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["product_list"] = Product.objects.all().order_by("-id")
        return context
    


class AboutView(TemplateView):
    template_name = "about.html"

class AllProductsView(TemplateView):
    template_name = "allproducts.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["allcategories"] = Category.objects.all()
        return context
    
class ProductDetailView(TemplateView):
    template_name = "productdetail.html"   

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        product.view_count += 1
        product.save()
        context["product"] = product
        return context

templates/about.html
{% extends "base.html" %}

{% block title %}
About
{% endblock %}

{% block content %}
<h1>

    This is about page
</h1>
{% endblock %}

templates/allproducts.html
{% extends "base.html" %}

{% block title %}All Products{% endblock %}

{% block content %}
<div class="container">
     <h3>All Products</h3><hr>
     {% for cat in allcategories %}
        <h4>{{cat.title}}</h4>
        <hr>
        <div class="row">
            {% for i in cat.product_set.all %}
            <div class="col-md-3" >
                <div class="m-4">
                    
                    
                    <h4><a href="{% url 'ecomapp:productdetail' i.slug %}">{{i.title}}</a></h4>
                    <img src="{{i.image.url}}" alt="" class="img-fluid" style="height: 2500;object-fit: cover;">
                    <p class="mt-3">Price: <strike>Rs. {{i.marked_price}}</strike> Rs.{{i.selling_price}}</p>
                    <a href = "#" class ="btn btn-primary">Add To Cart</a>
                    
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}

</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    <a href="{% url 'ecomapp:home' %}">Home</a>
    <a href="{% url 'ecomapp:about' %}">About</a>
    <a href="/about/">Contact-Us</a>
    <a href="{% url 'ecomapp:allproducts' %}">All-Products</a>

    
    <br>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<hr>
<div class="container">
    
    
    <h1 class="text-center">This is ecommerce site</h1>
    <hr>
    <div class="row" mt-3>
        
        {% for i in product_list %}
        <div class="col-md-3" >
            <div class="m-4">
                

                <h3><a href="{% url 'ecomapp:productdetail' i.slug %}">{{i.title}}</a></h3>
                <img src="{{i.image.url}}" alt="" class="img-fluid" style="height: 2500;object-fit: cover;">
                <p class="mt-3">Price: <strike>Rs. {{i.marked_price}}</strike> Rs.{{i.selling_price}}</p>
                <a href = "#" class ="btn btn-primary">Add To Cart</a>
          
        </div>
        </div>
        {% endfor %}
        
    </div>
</div>
{% endblock %}

templates/productdetail.html
{% extends "base.html" %}

{% block title %}
{{product.title}}
{% endblock %}

{% block content %}
<div class="container">
    <h3>
       Product: {{product.title}}
    </h3><hr>
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            
        </div>
        <div class="col-md-6">
            
            <h4>{{product.title}}(Viewed {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: Rs. <strike>{{product.marked_price}}</strike> Rs. {{product.selling_price}} </h5>
            <a href="" class="btn btn-info">Add To Cart</a><hr>
            <p class="text-info">Warranty: {{product.warranty}}</p>
            <p class="text-info ">Return Policy: {{product.return_policy}}</p>
            <hr>
            <p>{{product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}